fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
expeditor_homepage:
    path:     /
    defaults: { _controller: AppBundle:Employe:index }
expeditor_employe:
    path:     /employe
    defaults: { _controller: AppBundle:Employe:index }    
expeditor_manager:
    path:     /manager
    defaults: { _controller: AppBundle:Manager:index } 
expeditor_manager_articles_list:
    path:     /manager/articles
    defaults: { _controller: AppBundle:Article:liste }
expeditor_manager_articles_add:
    path:     /manager/articles/add
    defaults: { _controller: AppBundle:Article:add }  
expeditor_manager_articles_update:
    path:     /manager/articles/update
    defaults: { _controller: AppBundle:Article:update }   
expeditor_manager_articles_delete:
    path:     /manager/articles/delete
    defaults: { _controller: AppBundle:Article:delete } 
expeditor_manager_employes_list:
    path:     /manager/employes
    defaults: { _controller: AppBundle:Employe:liste }
expeditor_role:
    path:     /role
    defaults: { _controller: AppBundle:Employe:role }
expeditor_bouchon:
    path:     /bouchon
    defaults: { _controller: AppBundle:Bouchon:index }
expeditor_manager_import_commandes:
    path:     /manager/import
    defaults: { _controller: AppBundle:Import:index }
app:
    resource: '@AppBundle/Controller/'
    type: annotation