expeditor_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
expeditor_employe:
    path:     /employe
    defaults: { _controller: AppBundle:Employe:index }
expeditor_manager:
    path:     /manager
    defaults: { _controller: AppBundle:Manager:index }
expeditor_manager_articles:
    path:     /manager/articles
    defaults: { _controller: AppBundle:Manager:articles }
app:
    resource: '@AppBundle/Controller/'
    type:     annotation